export const ABI = [
  { type: "function", name: "MINT_PRICE", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "TICKET_PRICE", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "totalLockedPrizePool", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "totalGlobalVolumeETH", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "topScorerPoolBalance", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "tournamentFinalized", inputs: [], outputs: [{ type: "bool" }], stateMutability: "view" },
  { type: "function", name: "topScorerFinalized", inputs: [], outputs: [{ type: "bool" }], stateMutability: "view" },
  { type: "function", name: "winningCountryId", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "finalTopScorer", inputs: [], outputs: [{ type: "string" }], stateMutability: "view" },
  { type: "function", name: "finalNationsCupPool", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "finalTopScorerPool", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  {
    type: "function", name: "getAllCountryPools",
    inputs: [],
    outputs: [{ name: "pools", type: "uint256[49]" }],
    stateMutability: "view",
  },
  {
    type: "function", name: "countryTotalSupply",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function", name: "userMintCount",
    inputs: [{ type: "address" }, { type: "uint256" }],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function", name: "userUnusedTickets",
    inputs: [{ type: "address" }],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function", name: "balanceOf",
    inputs: [{ type: "address" }, { type: "uint256" }],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function", name: "balanceOfBatch",
    inputs: [{ name: "accounts", type: "address[]" }, { name: "ids", type: "uint256[]" }],
    outputs: [{ type: "uint256[]" }],
    stateMutability: "view",
  },
  {
    type: "function", name: "getPlayerVotes",
    inputs: [{ name: "playerName", type: "string" }],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function", name: "getUserVotesForPlayer",
    inputs: [{ type: "address" }, { name: "playerName", type: "string" }],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function", name: "mintCountryNFT",
    inputs: [{ name: "countryId", type: "uint256" }, { name: "amount", type: "uint256" }],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function", name: "buyScorerTickets",
    inputs: [{ name: "quantity", type: "uint256" }],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function", name: "voteTopScorer",
    inputs: [{ name: "playerName", type: "string" }, { name: "votesToUse", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  { type: "function", name: "claimNationsCupRewards", inputs: [], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "claimTopScorerRewards", inputs: [], outputs: [], stateMutability: "nonpayable" },
  {
    type: "event", name: "CountryMinted",
    inputs: [
      { name: "user", type: "address", indexed: true },
      { name: "countryId", type: "uint256", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
      { name: "timestamp", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event", name: "TicketPurchased",
    inputs: [
      { name: "user", type: "address", indexed: true },
      { name: "quantity", type: "uint256", indexed: false },
      { name: "timestamp", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event", name: "VoteCast",
    inputs: [
      { name: "user", type: "address", indexed: true },
      { name: "playerName", type: "string", indexed: false },
      { name: "votes", type: "uint256", indexed: false },
      { name: "timestamp", type: "uint256", indexed: false },
    ],
  },
] as const;
